const cartaotitulo = document.querySelector('.cartao-titulo')
const divcard = document.querySelector('.card')
const cartaotexto = document.querySelector('.cartao-texto')
const cartaotexto2 = document.querySelector('.cartao-texto2')
const cartaotexto3 = document.querySelector('.cartao-texto3')
const enviar = document.querySelector('#enviar')
const cancelar = document.querySelector('#cancelar')
const corpo = document.querySelector('.corpo')
const botoes = document.querySelector('.botoes')
const image = document.querySelector('.img')

corpo.style.backgroundColor = 'black'
corpo.style.display = 'flex';
corpo.style.flexDirection = 'column'
corpo.style.flexWrap = 'wrap';
corpo.style.height = '100vh';
corpo.style.alignContent = 'center'
cartaotitulo.style.textAlign = 'center'
cartaotitulo.style.fontFamily = 'arial'
cartaotitulo.style.fontSize = '50px'
cartaotitulo.style.color = 'white'
divcard.style.border = '4px #303030 solid'
divcard.style.width = '50%'
divcard.style.alignContent = 'center'
divcard.style.borderRadius = '25px'
divcard.style.padding = '20px'
cartaotexto.style.color = 'white'
cartaotexto.style.fontSize = '30px'
cartaotexto.style.fontWeight = 'bold'
cartaotexto2.style.color = 'white'
cartaotexto3.style.color = 'white'
cartaotexto.style.fontFamily = 'arial'
cartaotexto2.style.fontFamily = 'arial'
cartaotexto3.style.fontFamily = 'arial'
cartaotexto.style.color = 'white'
cartaotexto2.style.color = 'white'
cartaotexto3.style.color = 'white'
image.style.borderRadius = '16px'
image.style.height = '300px'
image.style.width = '100%'
enviar.style.padding = '10px'
enviar.style.backgroundColor = '#181a1b'
enviar.style.borderRadius = '8px'
enviar.style.color = 'white'
enviar.style.textAlign = 'center'
enviar.style.fontWeight = 'bold'
enviar.style.fontFamily = 'arial'
enviar.style.border = '3px #303030 solid'
enviar.style.width = 'shrink'
enviar.style.marginTop = '20px'
enviar.style.fontSize = '20px'
enviar.style.cursor = 'pointer'
enviar.style.padding = '10px 50px'
image.style.width = '100%'
botoes.style.alignContent = 'center'
cancelar.style.padding = '10px'
cancelar.style.backgroundColor = '#181a1b'
cancelar.style.borderRadius = '8px'
cancelar.style.padding = '10px 50px'
cancelar.style.color = 'white'
cancelar.style.textAlign = 'center'
cancelar.style.fontWeight = 'bold'
cancelar.style.fontFamily = 'arial'
cancelar.style.border = '3px #303030 solid'
cancelar.style.width = 'shrink'
cancelar.style.marginTop = '20px'
cancelar.style.fontSize = '20px'
cancelar.style.cursor = 'pointer'
cancelar.style.marginLeft = '10px'


